### ISSUE TITLE
Users are not displayed on the users page

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#767] opened 2020-06-30 03:41 UTC
## Expected Behavior

I should be able to see users list in the "Users" page

## Current Behavior

Users are not listed
![image](https://user-images.githubusercontent.com/4447392/86080885-37a97500-ba94-11ea-9525-6ddd52c5eaa6.png)

## Steps to Reproduce

 - Creates an user with the admin console
 - Load the users list page

## Context (Environment)

Kuzzle version: 2.3.0
Admin Console Version: next-console.kuzzle.io (v4)

**Comment by Njuelle** [comment] 2020-06-30 12:25
I've tried, I can't reproduce this bug

**Comment by Njuelle** [comment] 2020-06-30 12:26
ooh I see, look at the URL in your screenshot ;)

**Comment by Aschen** [comment] 2020-07-01 03:52
So the pagination should be displayed or something.
I have this in my URL because on another Kuzzle I had more than 10 users but when I switch to this one I only had 2

**Comment by xbill82** [comment] 2020-07-02 07:42
Yes, we need a solution for this because you can actually get parms from another environment and get your results screwed by them. Maybe we should include the env name in all the search params and avoid to apply them if the current env doesn't correspond

**Comment by Aschen** [comment] 2020-07-02 08:05
IMHO it's not enough because you may have 20 users and then be on the 2nd page of results.  

If you delete 18 users with Kourou you will have the same behavior

**Comment by xbill82** [comment] 2020-07-02 12:32
it's more complicated than we thought, then. Because there are cases where you want your pagination to be kept through page reloads or navigation (e.g. if you edit a user on the Xth page and get back to the list)

**Comment by Aschen** [comment] 2020-07-03 03:32
Maybe just a visual feedback to indicate that some pagination is in effect and a button to reset to the first results ?

**Comment by berthieresteban** [comment] 2020-07-03 08:52
I think there is another problem...

Here the AC use the `security.searchUsers` method.
`No user defined` message is displayed only if the `total` property of the search result is equal to 0.
That property is based on the total results matching the query wich is good.
But IMHO the `from` and `size` query opions shouldn't change that value because the `fetched` result property is here for.

Example of `total` and `fetched` results of a `security.searchUsers` request (with only one user created):
no query specified, from=0 size=10 => res.total = 1 / res.fetched = 1
no query specified, from=1 size=10 => res.total = 0 / res.fetched = 0

It should be: 
no query specified, from=0 size=10 => res.total = 1 / res.fetched = 1
no query specified, from=1 size=10 => res.total = 1 / res.fetched = 0

**Comment by xbill82** [comment] 2020-07-03 13:19
Ok @berthieresteban I see you spotted some hell of a bug here, good job dude!
I totally agree with what you say. The `total` value should be issue from the Kuzzle `Response` object and tell the _really total_ result count of the documents matching the query. Once the `from` exceeds the `total`, we set `from` to 0.

**Comment by xbill82** [comment] 2020-07-03 13:20
@berthieresteban do you want to tackle this issue? (just assign yourself if affirmative)

**Comment by berthieresteban** [comment] 2020-07-08 09:14
@xbill82 I can tackle the AC side of that bug but I'm not sure to be able to fix the kuzzle side.
I'll open an issue on kuzzle repo

**Comment by scottinet** [comment] 2020-07-09 13:38
This should be fixed in the next version of Kuzzle: https://github.com/kuzzleio/kuzzle/pull/1713

**Comment by berthieresteban** [comment] 2020-07-15 09:39
Thanks to @scottinet the total property bug has been fixed.
I can now adapt the AC to fix the not displayed users BUT the bug will persist using previous versions of Kuzzle (with bugged total property)
What should we do ? ping @xbill82  @Njuelle @Aschen

**Comment by xbill82** [comment] 2020-07-20 13:46
I guess we can leave the "buggy" behavior when using the previous Kuzzle versions. My stand is that the concern of the AC is not to patch the bugs in the core, but to provide a GUI to administrate it. If the core bugs, the AC bugs...
I would then just fix the AC code based on the correct API behavior without polluting it with additional code for retro-compat. If people complain, my answer is "This bug has been fixed in Kuzzle 2.x.x, please update". 🤷

**Closed** 2020-11-19 15:35 UTC
Labels: 4-dev, bug, priority-blocking
