### ISSUE TITLE
Sidebar: cannot list index/collections with restricted rights

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#817] opened 2020-09-03 15:04 UTC
## Expected Behavior

When an user who have restricted rights on an index load the admin console, he can't see the sidebar content.

## Current Behavior

At least he user should see only the index he is allowed to read in the sidebar

## Steps to Reproduce

1. Create this role

<details><summary>reader</summary>

```
{
  "controllers": {
    "auth": {
      "actions": {
        "getCurrentUser": true,
        "getMyCredentials": true,
        "getMyRights": true,
        "logout": true,
        "refreshToken": true
      }
    },
    "collection": {
      "actions": {
        "getMapping": true,
        "list": true
      }
    },
    "document": {
      "actions": {
        "count": true,
        "get": true,
        "mGet": true,
        "scroll": true,
        "search": true
      }
    },
    "index": {
      "actions": {
        "list": true
      }
    },
    "ms": {
      "actions": {
        "hget": true,
        "hset": true
      }
    }
  }
}
```

</details>

Just run this and copy the entire content instead of `{}` just after `body: `
```
kourou security:createRole --id reader --editor
```

2. Create the corresponding profile

<details><summary>reader</summary>

```
{
  "rateLimit": 0,
  "policies": [
    {
      "roleId": "reader",
      "restrictedTo": [
        {
          "collections": [
            "alarm"
          ],
          "index": "mydata"
        },
        {
          "collections": [
            "access"
          ],
          "index": "logs"
        }
      ]
    }
  ]
}
```

</details>

Just run this and copy the entire content instead of `{}` just after `body: `
```
kourou security:createProfile --id reader --editor
```

3. Create an user with the profile

```
kourou security:createUser --body '{"content":{"profileIds":["reader"]},"credentials":{"local":{"username":"reade","password":"reader"}}}'
```

4. Create those index/collections

```
kourou collection:create mydata alarm
kourou collection:create mydata provider

kourou collection:create logs access

kourou collection:create otherdata alarm
kourou collection:create otherdata console
kourou collection:create otherdata provider
```

5. Login to the Admin Console

username: `reader`
password: `reader`

## Context (Environment)

Admin Console Version: v3 and v4

**Comment by xbill82** [comment] 2020-09-16 15:45
This is going to be a won't fix.

The expected behavior looks more like a feature-request on the core than a bugfix here. Kuzzle core will not let any user list the indexes if the `index:list` action is restricted. This is a long ongoing discussion we have on the core and, for the time being, the arguments in favor of the current behavior are the winning ones.

The aim of the Admin Console is to provide a graphical access to the features of Kuzzle Core, not adding new ones. Since Kuzzle does not allow to see the list of the indexes with such rights and profiles, then the AC will not either.

The need here is to provide a meaningful message instead of a never stopping spinner.

**Comment by xbill82** [comment] 2020-09-17 06:43
Waiting for #826 to be completed before getting this done.

**Comment by Aschen** [comment] 2020-09-18 12:04
Here is a snippet to restrict index and collection list to users who can act on it: https://gist.github.com/Aschen/904d7f168dbd2234e4f1aa12f604b569

**Closed** 2021-04-20 11:10 UTC
Labels: 3-dev, 4-dev, discussion, wont-fix
