### ISSUE TITLE
List properties sub types in the select attribute box

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#861] opened 2020-12-18 09:32 UTC
## Description

Properties can have sub-types definitions in order to index the same property in different way (e.g. having a `text` and a `keyword` to allow full text search as well as fast exact matching)

The select attribute box only display the first type definition.

**Example of sub-type definition:**
![image](https://user-images.githubusercontent.com/4447392/102598391-3b9d8200-411c-11eb-9539-eeeb7f3c46ee.png)

**Sub-types are not displayed:**
![image](https://user-images.githubusercontent.com/4447392/102598463-5bcd4100-411c-11eb-87a2-e431d6914502.png)

**Comment by Njuelle** [comment] 2020-12-22 08:44
duplicate of #856

**Closed by Njuelle** 2020-12-22 08:44 UTC
Labels: 4-dev, feature-request
