### ISSUE TITLE
e.refreshSearch is not a function

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#463] opened 2018-10-07 09:50 UTC
After a fresh installation of Kuzzle 1.5 and using console.kuzzle.io (2.2.2), after deleting an user, I have an error : e.refreshSearch is not a function

Step to reproduce : 

Create a kuzzle user using API (my use case)
Go to console.kuzzle.io
Find the fresh new user
Delete using the trash icon
Constat the error

**Comment by Tyki** [comment] 2018-10-08 14:20
I have Chrome 69 on a Macbook

**Comment by Aschen** [comment] 2018-10-09 07:30
Ok I reproduce it:
  - Install SDK JS 6: 
  - Create user with this script: https://gist.github.com/Aschen/659c8bd8dcea8bfc43cde7290ee96b6e
  - Open admin console -> Security tab
  - Select newly created user and user the `DELETE` button

**Comment by Tyki** [comment] 2019-02-05 09:48
@Aschen issue is back with console 2.2.3

**Comment by jenow** [comment] 2019-03-19 13:28
I cannot reproduce in 2.2.9, can you tell me if you still have the problem and close this issue otherwise? Thanks :)

**Closed** 2020-04-28 10:38 UTC
Labels: bug, priority-normal
